version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
# maven bot configurations
- package-ecosystem: "maven"
  directory: "/"
  schedule:
    interval: "monthly"
  open-pull-requests-limit: 20
# Yarn bot configurations
- package-ecosystem: "npm"
  directories:
  - "/"
  schedule:
    interval: "monthly"
  open-pull-requests-limit: 20
